### ISSUE TITLE
Using ros_control diff_drive_controller

### ISSUE THREAD

**Issue by paulbovbel** [ros/urdf_tutorial#12]
Hi, I am working on adapting the R2D2 URDF tutorial to use ros_control's diff_drive_controller (http://wiki.ros.org/diff_drive_controller) together with the gazebo_ros_control plugin, replacing the older:

- differential_position2d
- gazebo_ros_p3d
- gazebo_ros_controller_manager

(https://github.com/ros/urdf_tutorial/blob/master/urdf/r2d2.xacro#L245)

Would you be amenable to a pull request to this repo, and having me add another tutorial to the http://wiki.ros.org/urdf/Tutorials page?

**Comment by DLu** [comment]
That sounds good to me. I had always intended to extend the R2D2 URDF tutorial to include gazebo simulation, but it wasn't until recently that I actually figured out how it works.
