### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by wjwwood** [ros/urdf_tutorial#13]
This is included in desktop-full: http://wiki.ros.org/jade/Planning/Maintenance

@DLu do you have time to do this release?

**Comment by DLu** [comment]
I just started working on it today. I'm waiting to hear back from @isucan about his maintainer status.

**Comment by isucan** [comment]
David, i am unable to do anything for this until next week. If you'd like
to become the maintainer for this, that would be very helpful. Doing this
release alone would also be very helpful. Thanks!

**Comment by DLu** [comment]
Hrm. So urdf_tutorial has a runtime dependency on pr2_description because it uses [meshes from the pr2 gripper](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch#Finishing_the_Model)

Should I 
A) Save local versions of the meshes
B) Wait for a [jade release](https://github.com/PR2/pr2_common/issues/239) of pr2_description? 
C) Remove the run_depends but not the code. 
D) Panic. 
E) Something else
?

**Comment by wjwwood** [comment]
It would be nice not to have to depend on `pr2_description`, but it seems like `pr2_common` could be released if `convex_decomposition` (https://github.com/ros/convex_decomposition/issues/2) and `ivcon` (https://github.com/ros/ivcon/issues/2) get released. If it can get done in the short term, I'd say `B)`.

**Comment by DLu** [comment]
Not sure if there's going to be any movement on the jade release of pr2_common. 

If I went with A, would the best method be a literal copy and paste of the files, or something else, do you think?

**Comment by wjwwood** [comment]
Copying it would be fine. Though, I think part of the tutorial is to show that you can use resources from outside of the package you are in. Given the list of not so good options, I guess we go with A.

**Comment by wjwwood** [comment]
Hold on that, @TheDash gave me permission to get pr2_description released. I'll do it now.

**Comment by wjwwood** [comment]
Ok, pr2_common is in flight: https://github.com/ros/rosdistro/pull/8241

Once that's merged then you should be clear to release this @DLu, thanks for your help!

**Comment by wjwwood** [comment]
@DLu I'd like to get this out today, do you have time, or should I do it?

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/8257

**Comment by wjwwood** [comment]
Thanks!
