### ISSUE TITLE
Wiki Changes for ROS Control Changes

### ISSUE THREAD

**Issue by DLu** [ros/urdf_tutorial#15]
- [x] [Minor updates to material tags and gazebo materials](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch)
- [x] [Minor updates for dynamic parameters/gazebo dynamic tags](http://wiki.ros.org/urdf/Tutorials/Adding%20Physical%20and%20Collision%20Properties%20to%20a%20URDF%20Model)
- [x] [Major update with xacro cleanup](http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File)
- [x] New section required: Integrating with Gazebo and ROS Control

**Comment by DLu** [comment]
Can't assign @paulbovbel  for some reason.

**Comment by paulbovbel** [comment]
Maybe if I'm a participant. Either way, will take a whack on Friday.

**Comment by DLu** [comment]
Any progress here?

**Comment by paulbovbel** [comment]
Mea culpa, not yet, will find some time asap.

**Comment by paulbovbel** [comment]
Eep, thank you @dlu for doing the heavy lifting.
