### ISSUE TITLE
missing roslaunch dependency

### ISSUE THREAD

**Issue by tkruse** [ros/urdf_tutorial#16]
I believe since CMakeLists.txt find_packages roslaunch, it should be listed in package.xml as build_depend

**Comment by tkruse** [comment]
Actually, I need to confirm, closing meanwhile.

**Comment by tkruse** [comment]
Yes, without the dependency, I get
```
CMake Error at /home/kruset/work/ros/jade_sources/devel/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "roslaunch" with
  any of the following names:

    roslaunchConfig.cmake
    roslaunch-config.cmake
```

**Comment by DLu** [comment]
I can't replicate the error, but agree that it should be included. Pull request?

**Comment by DLu** [comment]
Actually, it is a run dependency, so should we just remove it from the find_package command?

**Comment by tkruse** [comment]
I believe it is build-required for this:
```
roslaunch_add_file_check(launch)
```

**Comment by tkruse** [comment]
and the build fails accordingly:
```
CMake Error at CMakeLists.txt:7 (roslaunch_add_file_check):
  Unknown CMake command "roslaunch_add_file_check".

```
