### ISSUE TITLE
How run urdf in Gazebo

### ISSUE THREAD

**Issue by MAS94** [ros/urdf_tutorial#18]
Ok, I am new to ROS and gazebo. I have already gone through the online tutorials. The online gazebo tutorial is very vague about how to take a urdf file and run it on gazebo. Can someone explain to me how to take a urdf file (running in rviz) and run it on Gazebo. 

PS. I know about the including inertia and other tags for gazebo.

**Comment by DLu** [comment]
Hi. Please use the Issues feature for reporting bugs or suggesting improvements. Please use answers.gazebosim.org or answers.ros.org for general support inquiries. 

There is a urdf_tutorial-branded Gazebo tutorial in the works, but it is not available yet.
