### ISSUE TITLE
Combining tf data and URDF model

### ISSUE THREAD

**Issue by tunaonur** [ros/urdf_tutorial#21]
Hi, I have a human URDF model that I can display in Rviz and I am getting tf data from Kinect v2. I am trying to place human URDF model on the tf data so I will have a chance to see the human URDF model moving instead of lines representing skeleton. Is there way for me to do that? Thanks a lot!

**Comment by DLu** [comment]
There is, but please open this as a ROS Answers question instead of an issue. Thanks!
