### ISSUE TITLE
Update urdf_tutorial to not depend on pr2_common repository

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/urdf_tutorial#23]
@wjwwood FYI: opening this as discussed offline

**Comment by DLu** [comment]
Previous discussion was here: https://github.com/ros/urdf_tutorial/issues/13

What was the thinking offline?

**Comment by mikaelarguedas** [comment]
@DLu thanks for the pointer I didn't look at the closed issues :confounded: 
The thinking offline was the following:
- It is inconvenient to depend on the entire pr2 stack just for a few resources from one of its packages
- This will allow to shrink the number of dependencies of desktop-full and curate a bit the different licences it contains (ivcon being CPL)
- It will permit to move faster in the release process of the next ros release

The details of where the resources should be put instead hasn't been discussed and I'll leave that up to @wjwwood to decide what is the best solution

**Comment by DLu** [comment]
What do you say, @wjwwood? I'm thinking of copying the mesh to urdf_tutorial, but defer to higher powers.

**Comment by wjwwood** [comment]
I think @mikaelarguedas has moved to get `pr2_description` released. It seems to me that referencing an external resource from another package has value in the tutorial. And referencing a "real" robot mesh makes it feel more authentic. However, copying the mesh to this repository (or just making a new gripper up), in its own package or not, is fine by me. It certainly has been annoying to have to wait on `pr2_description` each time.
