### ISSUE TITLE
xacrodisplay.launch is missing

### ISSUE THREAD

**Issue by Kukanani** [ros/urdf_tutorial#26]
While going through http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File, I discovered that `xacrodisplay.launch` is now missing from the `launch` directory, causing fatal errors when trying to run the tutorial. The file is still located in `indigo`, but is missing in `default`. I can't locate the commit that removed it, but it seems to have disappeared between 1697f8c and 4b343d6.

**Comment by mikaelarguedas** [comment]
The file disappeared in https://github.com/ros/urdf_tutorial/pull/14/commits/9d38b7b4da3e00bdbd17148676a86be61849293d from #14

**Comment by DLu** [comment]
Closed with http://wiki.ros.org/action/diff/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File?action=diff&rev1=21&rev2=22
