### ISSUE TITLE
rviz doesn't show any shape

### ISSUE THREAD

**Issue by Maik93** [ros/urdf_tutorial#33]
Hi,
I'm trying to build my first URDF model, following this tutorial:
http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch

Booth replicating what's done there and cloning your repo, I can't see any mash or shape in rviz, only transformations; here's what I see from [chap.4](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch#Material_Girl) code:

![image description](http://imageshack.com/a/img924/7439/FGZxFt.jpg)

There should be cylinders and squares...

Anyone experiencing this issue? I'm running ROS Lunar, Ubuntu 17.04 x64 on VirtualBox 5.1.18 (with "3D acceleration" disabled because i don't know why, if it's enabled rviz trows segmentation faults at start)

Side note: [chap.1](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch#One_Shape) I think it's buggy because with no joints there's not any "base_link" transformation supplied by joint_state_publisher, and Rviz go crazy...

**Comment by DLu** [comment]
Please don't double-post your problems. answers.ros.org is the appropriate venue for this question.
https://answers.ros.org/question/271357/rviz-doesnt-show-any-shape/
