### ISSUE TITLE
Problem with "RobotModel" in Rviz

### ISSUE THREAD

**Issue by ghx-0228** [ros/urdf_tutorial#38]
I just execute the examples in your tutorial without any change. But all examples, except the 1st one, have such a problem "no transform from [] to []" as shown in the following figure.
![image](https://user-images.githubusercontent.com/47413096/59585879-1a696900-9114-11e9-97a5-99e33487d39b.png)

However, when I add "RobotState", it is alright, like this.
![image](https://user-images.githubusercontent.com/47413096/59585963-5270ac00-9114-11e9-8073-e882a242573f.png)
So could you help me solve the above problem?

**Comment by DLu** [comment]
The provided rviz configuration uses `/base_link` as the root frame, rather than `/map` which is the default. If you change the global fixed frame to `base_link` it will resemble the RobotState.

**Comment by ghx-0228** [comment]
The global fixed frame was just /base_link. The "StateModel" had many "transform" errors
![image](https://user-images.githubusercontent.com/47413096/59743414-a14c4c00-92a2-11e9-825f-47efa3f358a4.png)

**Comment by DLu** [comment]
Seems like you might be out of sync with the different steps of the tutorial, as if robot_state_publisher was seeing the previous version of the URDF. It doesn't automatically reload when the parameter changes.

**Comment by vec123** [comment]
Hmmm i am having a very similar issue, where i get an transform error on a seemingly correct urdf (meaning e.g. i have a first link, then a follow_up joint which specifies the child link of that fist link and the chain continues like this).  Now I expected that, when the first link is published to rviz, that then the chain would be processed, and therefore all links displayed. However this is the output:

![image](https://user-images.githubusercontent.com/55460310/77857756-cb527780-71ff-11ea-97c0-e2bf064d7675.png)

The loaded launchfile loads the robot model like this:

`<arg name="bin" default="$(find peg_in_hole)/urdf/r2d2.urdf"/>
 <param name="r2d2/robot_description" command="$(find xacro)/xacro $(arg bin)" />
  
and the two ( as far as i know) necessary nodes like this:

  <node pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher"/>
    <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher"/>

   <node name="rviz" pkg="rviz" type="rviz" required="true" />
. 

I would expect these lines of code to load the .urdf description (which is correctly written, copied out of the tutorial) and publish the joints to /joint_states from where it goes to /tf and results in the display of the links.

I am pretty new to this so maybe i got something wrong. I can only tell that the joints never arrive at /joint_states, so i am guessing that something is missing, but i don't know what and can't seem to find anything.




`
