### ISSUE TITLE
Robot_model tf_error 

### ISSUE THREAD

**Issue by vec123** [ros/urdf_tutorial#41]
Hi, i am having a very similar issue to " https://github.com/ros/urdf_tutorial/issues/38" , where i get an transform error on a seemingly correct urdf (meaning e.g. i have a first link, then a follow_up joint which specifies the child link of that fist link and the chain continues like this). Now I expected that, when the first link is published to rviz, that then the chain would be processed, and therefore all links displayed. However this is the output:
![image](https://user-images.githubusercontent.com/55460310/77857756-cb527780-71ff-11ea-97c0-e2bf064d7675.png)

The loaded launchfile loads the robot model like this:

`<arg name="bin" default="$(find peg_in_hole)/urdf/r2d2.urdf"/>`

`<param name="r2d2/robot_description" command="$(find xacro)/xacro $(arg bin)" />`

`<node pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher"/>`
`<node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher"/>`

`<node name="rviz" pkg="rviz" type="rviz" required="true" />`

I would expect these lines of code to load the .urdf description (which is correctly written, copied out of the tutorial) and publish the joints to /joint_states from where it goes to /tf and results in the display of the links.

I am pretty new to this so maybe i got something wrong. I can only tell that the joints never arrive at /tf or /tf_static, so i am guessing that something is missing, but i don't know what and can't seem to find anything.

`

**Comment by DLu** [comment]
This is probably more appropriate for answers.ros.org, but `joint_state_publisher` and `robot_state_publisher` expect the parameter name to be `robot_description` by default, and by changing it to `r2d2/robot_description` I am guessing that they aren't finding the proper configuration.
