### ISSUE TITLE
Release urdf_tutorial into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros/urdf_tutorial#42]
Would you mind releasing `urdf_tutorial` to ROS Noetic? It looks like all of its dependencies have been released, and `metapackages` needs it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by sloretz** [comment]
Would be nice to have #43 to avoid a CMake warning on the build farm when building this package.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/24872
