### ISSUE TITLE
Create new branch for ROS2

### ISSUE THREAD

**Issue by knatsuki** [ros/urdf_tutorial#44]
Hi, I have a branch up in https://github.com/knatsuki/urdf_tutorial/commit/36c3fba147b046c7f35e1fd92a1c4a1c98bfed21 that ports over the tutorial to ros2 foxy. Since it's using the new launch substitution syntax, it won't work for eloquent or below. If you create a new branch in the repo, I'd be happy to put a PR up. Let me know, thanks!

**Comment by DLu** [comment]
Done and done: https://github.com/ros/urdf_tutorial/network

There's now ros1 and ros2 branches.

**Comment by DLu** [comment]
(please do open a PR)
