### ISSUE TITLE
Assorted minor errors

### ISSUE THREAD

**Issue by beverlylytle** [ros/urdf_tutorial#46]
I recently went through the tutorial and encountered the following issues:
1. The image `multipleshapes.png` includes a box of dimensions .6m x .2m x .1m rather than what is written in the urdf (ie .6m x .1m x .2m).
2. In both `05-visual.urdf` and `06-flexible.urdf`, the link `right_front_wheel` has a visual element with two different origins.

**Comment by DLu** [comment]
Thanks for pointing these out!
