### ISSUE TITLE
how install this package with ROS Humble and Gazebo Fortress

### ISSUE THREAD

**Issue by dvogureckiy99** [ros/urdf_tutorial#62]
Hi, how install this package with ROS Humble and Gazebo Fortress ?
```Package 'urdf_tutorial' not found: "package 'urdf_tutorial' not found, searching:```

I encountered errors:
1. ```Captured stderr output: warning: No module named 'rosgraph'```
2. ```Captured stderr output: error: No such file or directory: urdf/01-myfirst.urdf```
3.
```
CMake Error at /home/dvogureckiy99/ros2_humble/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:41 (if):
  if given arguments:

    "ament_cmake_core" "IN_LIST" "_ARG_EXCLUDE"

  Unknown arguments specified
```

**Comment by DLu** [comment]
This package is released with the ROS 2 binaries, so on Ubuntu `apt install ros-humble-urdf-tutorial` should work. 

If you are having other errors, please provide the exact command and the full output.

**Comment by dvogureckiy99** [comment]
> This package is released with the ROS 2 binaries, so on Ubuntu `apt install ros-humble-urdf-tutorial` should work.
> 
> If you are having other errors, please provide the exact command and the full output.

E: Unable to locate package ros-humble-urdf-tutorial

**Comment by DLu** [comment]
What OS?

**Comment by dvogureckiy99** [comment]
> What OS?

Ubuntu 20.04

**Comment by DLu** [comment]
Unfortunately binaries are not available for Humble + 20.04
https://www.ros.org/reps/rep-2000.html#humble-hawksbill-may-2022-may-2027

Are you set on using Humble?

**Comment by dvogureckiy99** [comment]
I installed Humble from source. It's not the problem.

**Comment by DLu** [comment]
Then you should also install this package from source.

**Comment by cccccmake** [comment]
> Then you should also install this package from source.

Hi! I've got some issue when I try building the package from source. I got the following workspace structure:

![image](https://github.com/ros/urdf_tutorial/assets/39816715/50a4cffb-5465-4d0f-a999-fe46f70b6cff)

And after I run `colcon build` under the root of my workspace, I got the following outputs:

```
--- stderr: urdf_tutorial                         
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.
---
```

It asks for a configuration file for catkin. After I clean up the outputs of the colcon and run`catkin build`, it still asks me for catkin's config.

As for the OS, I'm running ros2 humble on arch.

Could you please offer me some suggestions regarding this issue?

**Comment by DLu** [comment]
@cccccmake This appears to be an entirely separate issue, but please make sure you have the `ros2` branch checked out.

**Comment by AmeyaB2005** [comment]
![Screenshot 2024-06-09 213904](https://github.com/ros/urdf_tutorial/assets/146567207/3baf07e0-64a7-4914-b9ca-a1c62a596688)
i am getting error and unable to download urdf_tutorial

**Comment by guotong1988** [comment]
ERROR:
`package 'urdf_tutorial' not found`

FIX:
`sudo apt install ros-jazzy-urdf-tutorial`

**Comment by DLu** [comment]
@guotong1988 [It's there in Jazzy](https://repo.ros2.org/status_page/ros_jazzy_default.html?q=urdf_tutorial). Make sure you `sudo apt update` first.
