### ISSUE TITLE
where to get urdf_launch package?

### ISSUE THREAD

**Issue by suresh-venkate** [ros/urdf_tutorial#66]
Hi,

I am trying to install this package for ROS2 - Humble. When I run rosdep, I get the following error:

'Unable to locate package ros-humble-urdf-launch'

How can I install the urdf-launch package for humble distro?

**Comment by SyedMIrtazaHyder** [comment]
Check: https://github.com/MetroRobots/urdf_launch

**Comment by DLu** [comment]
The official home is now: https://github.com/ros/urdf_launch

It's working its way through the build farm now.
