### ISSUE TITLE
Potetial Issue with launch file

### ISSUE THREAD

**Issue by zacharyyamaoka** [ros/urdf_tutorial#68]
in https://github.com/ros/urdf_tutorial/blob/ros2/launch/display.launch.py

line 23 ->    ld.add_action(DeclareLaunchArgument(name='model', default_value=str(default_model_path),
                                        description='Path to robot urdf file relative to urdf_tutorial package'))

I belive there shouldn't be the str() there. It prevents the default value from actually working!

**Comment by clalancette** [comment]
> I belive there shouldn't be the str() there. It prevents the default value from actually working!

Yep, you are absolutely correct.  Removing that `str` makes it work.  I'll submit a PR to fix it right now.  Thanks!

**Comment by DLu** [comment]
Good catch, thanks!
